site_name: NOAA Omics Study Data Templates
theme:
  name: readthedocs
  highlightjs: true
extra_css: [style_2.css]
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Home: 'index.md'
  - 'Study Data Templates': 'study-data-templates.md'
  - 'Contributors': 'contributors.md'
use_directory_urls: false

