site_name: NOAA Omics Study Data Templates
theme:
  name: readthedocs
  highlightjs: true
extra_css: [style_2.css]
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - 'Study Data Templates' : 'index.md'
  - 'NCBI Submission Instructions': 'ncbi.md'
  - 'OBIS/GBIF Submission Instructions': 'obis.md'
  - 'Contributors': 'contributors.md'
use_directory_urls: false

